whichday-oidc-issuer-uri: ENC[AES256_GCM,data:89iieTGdc2/So8mZz5ish6+EBS63IyatK2yB,iv:lFtR0w7l+AKCVzAueoPsLsOAkxBSKPTlhaY9D9B7ehM=,tag:rE3X1B+hils+P/sasnYtCw==,type:str]
whichday-oidc-client-id: ENC[AES256_GCM,data:TonGHuThu+5y/aCc0sBEqHoaV7/pxbpF5cO7qRHIEfG4BKEs671dmZ3kqKaNXzHFDeePekP1eRZv/vFs7dVaBbRZwCTEP9Ra,iv:2eLBuPSkPWD3WqD1JI5Y2S7IVwz2L/C2Eh1JliAp1Kw=,tag:cdt9MqV3Msv3JoMh93kANA==,type:str]
whichday-oidc-client-secret: ENC[AES256_GCM,data:kjZh7F6S3dTUOVP7w8QyXv71kQSSzRI4D/QaBUTMInZRPkI=,iv:qoqkj8E74afUPVIlH+3dFp6Yc7UG0edfIQtZ/X209dM=,tag:vWC2Dh9V0SneFjs6CDUhFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdTVzSnVrVW9XbWhTanpl
            TTl2bDY0YzUrcFozSWMyYUZ3MVpxbVA4MHc0CnIrYnptcVRKdFVydU15MXN0Z3BB
            NDdqQ20vQTV6ZHBBME9ja3dFT1ZRS2cKLS0tIGNwZFVhZXJ6MmgxVllCSzFXeTVH
            b1l1UHp1OXJwTWdoR2JWQWl4elJBd0kKGjZ/L8Yva8qZhCMNszspo5IJIPDut/cS
            iQqx0Mpd4q1SN+ieTRAQpyJiSj//apuVRyYlweRgdxjLW11WqDS2vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17nj7rr7s5twjv5mes98c62lgx6qqflfcpna623gd8qfzlfza74us7g2nh2
    lastmodified: "2026-08-24T12:58:48Z"
    mac: ENC[AES256_GCM,data:KU8kGMQIsZJOy44fW+FoEJqPgUuJN3e8EL8pJ72Wsq9/jSbHN4PUNb5PucEp5LHFpTM2jpd/zpPLMyUdncdkNyFIVY1vzpMI1HBfCmbZB2Lhpu1rlv6K9TAx6huXIOUdQ70dSfej6G7PLEW8DDh0X3YH24+WikgcDLC24Otw/yk=,iv:cAwNhQY43jSP34FnXx+M+Vm6/ZB6zyXaGu9T9tT72A8=,tag:6xYxd/wTBieCTPp8hmqelw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
