name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'ansible/apps/**'
      - 'ansible/playbooks/deploy_apps.yml'
      - 'ansible/roles/application/**'

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/ansible-run.yml
    with:
      playbook: playbooks/deploy_apps.yml
    secrets: inherit
