storage:
  type: sqlite
  path: /data/data.db
  caching: true

ui:
  title: CloudyHome status
  header: CloudyHome status

endpoints:
  - name: calculators
    group: apps
    url: https://calc.cloudyhome.org/
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"

  - name: nasplan
    group: apps
    url: https://nasplan.cloudyhome.org/
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"

  - name: whichday
    group: apps
    url: https://whichday.cloudyhome.org/
    interval: 60s
    client:
      ignore-redirect: true
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[CERTIFICATE_EXPIRATION] > 72h"

  - name: frankfurter-mcp
    group: mcp
    url: https://frankfurter-mcp.cloudyhome.org/mcp
    interval: 60s
    conditions:
      - "[STATUS] < 500"
      - "[CERTIFICATE_EXPIRATION] > 72h"

  - name: binarycodes-dev-blog
    group: apps
    url: https://blog.binarycodes.dev/
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
